jberet/jsr352

jberet-core/src/main/java/org/jberet/runtime/runner/ChunkRunner.java

Clear output list with skipped elements.

Fixed JBERET-122.

---

jberet-se/src/main/java/org/jberet/se/Main.java

Let me know if filing an issue in JIRA is needed.

fix wrong FQCN in usage.

---

jberet-support/src/main/java/org/jberet/support/io/JdbcItemWriter.java

Previous PR: https://github.com/jberet/jsr352/pull/31

JBERET-138 Make JdbcItemWriter work with local transaction.

---

jberet-core/src/main/java/org/jberet/creation/ArchiveXmlLoader.java
jberet-core/src/main/java/org/jberet/job/model/JobParser.java

Previous PR: https://github.com/jberet/jsr352/pull/33

JBERET-139 Implement XMLResolver for Job XML parsing.

---

jberet-core/src/main/java/org/jberet/runtime/runner/ChunkRunner.java

Chunk commit can cause errors that can't be handled / JDBC job repository can cause deadlock

JBERET-146 Chunk commit can cause errors that can't be handled / JDBC job repository can cause deadlock

---

jberet-core/src/main/java/org/jberet/_private/BatchMessages.java
jberet-core/src/main/java/org/jberet/runtime/runner/AbstractRunner.java
jberet-core/src/main/java/org/jberet/runtime/runner/BatchletRunner.java
jberet-core/src/main/java/org/jberet/runtime/runner/ChunkRunner.java
jberet-core/src/main/java/org/jberet/runtime/runner/FlowExecutionRunner.java
jberet-core/src/main/java/org/jberet/runtime/runner/JobExecutionRunner.java
jberet-core/src/main/java/org/jberet/runtime/runner/SplitExecutionRunner.java
jberet-core/src/main/java/org/jberet/runtime/runner/StepExecutionRunner.java
jberet-core/src/main/java/org/jberet/spi/BatchEnvironment.java
jberet-core/src/main/java/org/jberet/spi/JobExecutor.java
jberet-core/src/main/java/org/jberet/spi/JobTask.java
jberet-core/src/test/java/org/jberet/test/JobRepositoryTest.java
jberet-se/src/main/java/org/jberet/se/BatchSEEnvironment.java
jberet-se/src/test/java/org/jberet/se/BatchSEEnvironmentTest.java

Here's my proposed changes. I can't decide if the `BatchEnvironment.submitTask(Runnable)` should be changed to `BatchEnvironment.submitTask(JobTask)` or not. I like the idea of not changing the SPI, but on the other hand a breaking change does indicate something needs to be changed.

[JBERET-180] Add a JobExecutor used to manage batch tasks.

---

jberet-core/src/main/java/org/jberet/runtime/runner/StepExecutionRunner.java
test-apps/chunkPartition/src/main/java/org/jberet/testapps/chunkpartition/ChunkPartitionMapper.java
test-apps/chunkPartition/src/main/resources/META-INF/batch-jobs/org.jberet.test.chunkPartitionFailComplete.xml
test-apps/chunkPartition/src/main/resources/META-INF/batch-jobs/org.jberet.test.chunkPartitionRestart2StepsMapper.xml
test-apps/chunkPartition/src/main/resources/META-INF/batch-jobs/org.jberet.test.chunkPartitionRestart2StepsMapperOverride.xml
test-apps/chunkPartition/src/test/java/org/jberet/testapps/chunkpartition/ChunkPartitionIT.java
test-apps/chunkPartition/src/test/java/org/jberet/testapps/chunkpartition/ChunkPartitionRestartIT.java
test-apps/common/src/main/java/org/jberet/testapps/common/IntegerArrayReader.java

port of #69 to 1.2.x branch
JIRA: https://issues.jboss.org/browse/JBEAP-4847

[JBEAP-4847] NPE in retry after a partitioned chunk

---

pom.xml
test-apps/chunkPartition/pom.xml
test-apps/restAPI/pom.xml

add jdk9-specific properties in modularizedJdk profile.

JBERET-281  Upgrade parent pom to jboss-parent 21

---

jberet-core/src/main/java/org/jberet/spi/JobExecutor.java

- Removed duplicate code and placed second condition with first

JBERET-234 Removed duplicate code

---

jberet-core/src/main/java/org/jberet/operations/AbstractJobOperator.java

@chengfang What do you think of this? If you'd rather not have it in JBeret I can easily do it other ways this is just for convenience.

Allow the user to be set for the start and restart job operations.

---

pom.xml
test-apps/jdbcBatchletReaderWriter/pom.xml

Small fixes to get build working.

Dependency fixes for tests.

---

jberet-core/src/main/java/org/jberet/repository/JdbcRepository.java

Issue: https://issues.jboss.org/browse/JBERET-417

[JBERET-417] Incorrect jberet batch status is shown when using JDBCRepository and multiple nodes

---

jberet-core/src/main/java/org/jberet/repository/JdbcRepository.java
pom.xml

Issue: https://issues.jboss.org/browse/JBEAP-14733
Upstream issue: https://issues.jboss.org/browse/JBERET-417
Upstream PR: https://github.com/jberet/jsr352/pull/113

[JBEAP-14733] Incorrect jberet batch status is shown if we have multiple standalone node involved.

---

jberet-core/src/main/java/org/jberet/runtime/SerializableData.java
jberet-core/src/main/java/org/jberet/spi/SerializableDataProvider.java
test-apps/pom.xml
test-apps/serialization/pom.xml
test-apps/serialization/src/main/java/org/jberet/testapps/serialization/JsonSerializableDataProvider.java
test-apps/serialization/src/main/java/org/jberet/testapps/serialization/SerializableBatchlet.java
test-apps/serialization/src/main/resources/META-INF/batch-jobs/batchlet.xml
test-apps/serialization/src/main/resources/META-INF/services/org.jberet.spi.SerializableDataProvider
test-apps/serialization/src/test/java/org/jberet/testapps/serialization/SerializationTest.java

Support additional Serialization mechanisms

---

jberet-core/src/main/java/org/jberet/operations/AbstractJobOperator.java
jberet-core/src/main/java/org/jberet/spi/BatchEnvironment.java
jberet-core/src/test/java/org/jberet/test/JobRepositoryTest.java
jberet-se/src/main/java/org/jberet/se/BatchSEEnvironment.java

Issue: https://issues.redhat.com/browse/JBERET-495

JBERET-495 Get application name from BatchEnvironment instead of jndi lookup

---

jberet-core/src/main/java/org/jberet/operations/AbstractJobOperator.java
jberet-core/src/main/java/org/jberet/spi/BatchEnvironment.java
jberet-core/src/test/java/org/jberet/test/JobRepositoryTest.java
jberet-se/src/main/java/org/jberet/se/BatchSEEnvironment.java

Issue: https://issues.redhat.com/browse/JBERET-495

JBERET-495 Get application name from BatchEnvironment instead of jnd lookup

---

jberet-core/src/main/java/org/jberet/operations/AbstractJobOperator.java
jberet-core/src/main/java/org/jberet/spi/BatchEnvironment.java
jberet-core/src/test/java/org/jberet/test/JobRepositoryTest.java
jberet-se/src/main/java/org/jberet/se/BatchSEEnvironment.java

Issue: https://issues.redhat.com/browse/JBERET-495

JBERET-495 Get application name from BatchEnvironment instead of jndilookup

---

README.md

Issue: https://issues.redhat.com/browse/JBERET-516

JBERET-516 Edit README to remove Unnecessary and old links

---

README.md
jberet-core/src/main/java/org/jberet/spi/DefaultJobOperatorContextSelector.java
project.properties
test-apps/common/src/main/java/org/jberet/testapps/common/AbstractIT.java

Issue: https://issues.redhat.com/browse/JBERET-511

Jberet-511 Replace Batch Applications for the Java Platform references in java doc with Jakarta Batch

---

jberet-core/src/main/java/org/jberet/repository/InfinispanRepository.java

https://issues.redhat.com/browse/JBERET-522

JBERET-522 Remove the use of TransactionManager in InfinispanRepository

---

pom.xml

Issue: https://issues.redhat.com/browse/JBERET-502

Upgrade Google guava from 25.1-jre to 30.0-jre

---

pom.xml

Issue: https://issues.redhat.com/browse/JBERET-491

JBERET-491 Upgrade batch api to 2.0.0.Final

---

README.md

Issue: https://issues.redhat.com/browse/JBERET-528

[JBERET-528] upadte README to add Jberet SE BOM details master

---

pom.xml

https://issues.redhat.com/browse/JBERET-535

JBERET-535 upgrade xmlbeans to 3.1.0 to work with poi 4.1.2

---

pom.xml

https://issues.redhat.com/browse/JBERET-538

JBERET-538 Upgrade jakarta batch api from 2.0.0 to 2.1.0-M2

---

pom.xml

https://issues.redhat.com/browse/JBERET-540

JBERET-540 Upgrade jakarta.inject-api from 2.0.0 from 2.0.1

---

pom.xml

https://issues.redhat.com/browse/JBERET-542

JBERET-542 Upgrade guava from 30.1-jre to 31.1-jre

---

pom.xml

https://issues.redhat.com/browse/JBERET-544

JBERET-544 Upgrade jakarta batch api from 2.1.0-M2 to 2.1.0

---

.github/workflows/ci.yml

JBERET-547 Add github action CI workflow

---

.github/workflows/jberet-1.x.yml
.github/workflows/jberet-2.x.yml

[1.3.x] JBERET-547 Add github action CI workflow

---

.github/workflows/jberet-1.x.yml
.github/workflows/jberet-2.x.yml

[master] JBERET-547 Add github action CI workflow

---

.github/workflows/jberet-1.x.yml
.github/workflows/jberet-2.x.yml

[1.4.x] JBERET-547 Add github action CI workflow (#201)

---

.github/workflows/jberet-1.x.yml
.github/workflows/jberet-2.x.yml

[1.3.9.SP] JBERET-547 Add github action CI workflow (#201)

---

jberet-core/src/main/java/org/jberet/repository/JdbcRepository.java

https://issues.redhat.com/browse/JBERET-543

[1.3.x] DDL location with MariaDB ... (#196)

---

jberet-core/src/main/java/org/jberet/repository/JdbcRepository.java

https://issues.redhat.com/browse/JBERET-543

[1.4.x] DDL location with MariaDB ... (#196)

---

pom.xml

https://issues.redhat.com/browse/JBERET-546

Upgrade jboss-marshalling from 2.0.6.Final to 2.0.12.Final

---

pom.xml

https://issues.redhat.com/browse/JBERET-542

[1.4.x] JBERET-542 Upgrade guava from 29.0-jre to 31.1-jre

---

pom.xml

Co-authored-by: Lorenzo Formenti <Lorenzo.Formenti@sia.eu>

JBERET-548 fix automatic module name with regex

---

pom.xml

Co-authored-by: Lorenzo Formenti <Lorenzo.Formenti@sia.eu>

JBERET-548 fix automatic module name with regex (#220)

---

jberet-core/src/main/java/org/jberet/creation/BatchCDIExtension.java
jberet-core/src/main/java/org/jberet/creation/JobOperatorProducer.java
pom.xml

https://issues.redhat.com/browse/JBERET-551

JBERET-551 Support injection of JobOperator

---

jberet-core/src/main/java/org/jberet/_private/BatchMessages.java
jberet-core/src/main/java/org/jberet/creation/AbstractArtifactFactory.java
jberet-core/src/main/java/org/jberet/creation/BatchBeanProducer.java
jberet-core/src/main/java/org/jberet/creation/ValueConverter.java

https://issues.redhat.com/browse/JBERET-554

JBERET-554 Support method param and constructor param injection of batch property

---

jberet-core/src/main/java/org/jberet/creation/BatchBeanProducer.java

https://issues.redhat.com/browse/JBERET-555

JBERET-555 Support CDI dynamic lookup of batch contexts and properties

---

jberet-core/src/main/java/org/jberet/creation/BatchBeanProducer.java

https://issues.redhat.com/browse/JBERET-557

JBERET-557 Check BatchProperty name attribute is empty instead of null

---

jberet-core/src/main/java/org/jberet/creation/BatchBeanProducer.java

https://issues.redhat.com/browse/JBERET-553

JBERET-553 Support injection into target of type jakarta.enterprise.inject.Instance

---

jberet-core/src/main/java/org/jberet/creation/BatchBeanProducer.java
test-apps/propertyInjection/src/main/java/org/jberet/testapps/propertyinjection/PropertyInjectionBatchlet.java

https://issues.redhat.com/browse/JBERET-558

JBERET-558 Refine the logic to check if the injection value target is primitive

---

pom.xml

https://issues.redhat.com/browse/JBERET-559

JBERET-559 Upgrade jboss-parent from 35 to 39

---

pom.xml

https://issues.redhat.com/browse/JBERET-560

JBERET-560 Upgrade jandex from 2.0.5.Final to 2.4.2.Final

---

pom.xml

https://issues.redhat.com/browse/JBERET-564

JBERET-564 Upgrade jakarta.el-api from 4.0.0 to 5.0.1

---

pom.xml

https://issues.redhat.com/browse/JBERET-566

JBERET-566 Upgrade jandex from 2.4.2.Final to 2.4.3.Final

---

pom.xml

https://issues.redhat.com/browse/JBERET-566

JBERET-566 Upgrade jandex from 2.0.5.Final to 2.4.3.Final

---

pom.xml
test-apps/pom.xml

https://issues.redhat.com/browse/JBERET-569

JBERET-569 add dependency nashorn-core for javascript support

---

pom.xml
test-apps/pom.xml
test-apps/purgeJdbcRepository/pom.xml
test-apps/purgeMongoRepository/pom.xml
test-apps/scripting/pom.xml

https://issues.redhat.com/browse/JBERET-570

JBERET-570 Configure maven pom to support building with jdk 17

---

pom.xml

https://issues.redhat.com/browse/JBERET-571

JBERET-571 Upgrade weld from 3.0.3.Final to 3.1.9.Final

---

pom.xml

https://issues.redhat.com/browse/JBERET-575

JBERET-575 upgrade jakarta.persistence from 2.2.3 to 3.1.0

---

pom.xml

https://search.maven.org/artifact/org.jberet/jberet-support/1.4.2.Final/jar

upgrade jberet-support from 1.3.3 to 1.4.2

---

pom.xml

https://issues.redhat.com/browse/JBERET-577

JBERET-577 Upgrade elytron from 1.19.0.Final to 2.0.0.Beta3

---

pom.xml

https://issues.redhat.com/browse/JBERET-578

JBERET-578 Upgrade jboss-marshalling from 2.0.12.Final to 2.1.0.Final

---

pom.xml

https://issues.redhat.com/browse/JBERET-581

JBERET-581 Upgrade jakarta.transaction-api from 2.0.0 to 2.0.1

---

.github/workflows/jberet-1.x.yml
.github/workflows/jberet-2.x.yml

https://issues.redhat.com/browse/JBERET-587

JBERET-587 Upgrade github actions to avoid github action warnings

---

.github/workflows/jberet-1.x.yml
.github/workflows/jberet-2.x.yml

https://issues.redhat.com/browse/JBERET-587

JBERET-587 Upgrade github actions to avoid github action warnings (#279)

---

README.md

Issue: https://issues.redhat.com/browse/JBERET-533

[JBERET-533] Update SE BOM (master) to 2.0.4 in ReadME

---

pom.xml

https://issues.redhat.com/browse/JBERET-588

JBERET-588 Upgrade cdi-api from 4.0.0 to 4.0.1

---

pom.xml

https://issues.redhat.com/browse/JBERET-589

JBERET-589 Upgrade elytron from 2.0.0.Beta3 to 2.0.0.Final

---

.github/dependabot.yml

https://issues.redhat.com/browse/JBERET-590

JBERET-590 Enable github dependabot [skip-ci]

---

pom.xml

https://issues.redhat.com/browse/JBERET-592

JBERET-592 Upgrade Guava for 31.1 to 32.1.1 (resolves CVE-2023-2976)

---

pom.xml

https://issues.redhat.com/browse/JBERET-593

JBERET-593 Upgrade jboss-logging from 3.5.0.Final to 3.5.3.Final

---

.github/workflows/jberet-manual.yml

https://issues.redhat.com/browse/JBERET-595

JBERET-595 Enable manual start of github actions CI workflow [skip ci]

---

.github/workflows/jberet-1.x.yml
.github/workflows/jberet-2.x.yml

https://issues.redhat.com/browse/JBERET-596

JBERET-596 Use github workflow cache action to speed up ci run

---

jberet-core/src/main/java/org/jberet/repository/JdbcRepository.java

Issue: https://issues.redhat.com/browse/JBEAP-26522 (EAP 8)
Upstream issue: https://issues.redhat.com/browse/JBERET-598
Upstream PR: https://github.com/jberet/jsr352/pull/453

JBERET-598: Mask db-creds from exception message

---

jberet-se/pom.xml
jberet-se/src/main/java/org/jberet/se/BatchSEEnvironment.java
jberet-se/src/test/java/org/jberet/se/BatchSEEnvironmentTest.java
pom.xml

JBERET-472: Extract database props from env-vars

---

.github/workflows/jberet-main.yml

Github. https://issues.redhat.com/browse/JBERET-599

[JBERET-599] Setup the CI testings against WildFly main branch on

---

pom.xml

Revert "Bump jakarta.annotation:jakarta.annotation-api from 2.1.1 to 3.0.0"

---

README.md

Issue: https://issues.redhat.com/browse/JBERET-534

[JBERET-534] Update SE BOM (1.4.x) to 1.4.6 in ReadME
